
 import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task Managment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
      <body className={inter.className}>
         
           
            <Header/>
            
            <div className="mt-3"> {children}</div> 
            
        
          
          
       
       </body>
    </html>
    
    
  );
}
